FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y

# prerequisited
RUN apt install -y  python3 && apt install -y python3-pip
RUN apt install -y python3-dev python3-setuptools build-essential python3-gevent python3-lxml libcairo2-dev git

RUN mkdir -p /fts-ui && mkdir -p /opt/fts-ui && mkdir -p /root/.ssh
WORKDIR /fts-ui
VOLUME ["/opt/fts-ui"]

RUN ssh-keyscan github.com >> /root/.ssh/known_hosts
RUN git clone --depth 1 https://github.com/FreeTAKTeam/UI.git .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -e .
RUN pip install Flask-SQLAlchemy==2.5.0

WORKDIR /fts-ui/FreeTAKServer-UI

RUN mv config.py config.py.orig
ADD ui-entry.sh ui-entry.sh

EXPOSE 5000

ENTRYPOINT [ "/bin/sh" , "-c", "./ui-entry.sh"]