version: '3.8'
services:
  fts:
    build:
      context: .
      dockerfile: Dockerfile.fts
    restart: always
    #command:
    #  - "-UI"
    #  - "True"
    volumes:
      - "./fts:/opt/fts"
    # uncomment after running ./setup.sh to avoid getting first time run again
      - "./fts/fts_installation_completed.json:/fts-server/FreeTAKServer/core/configuration/installation.json"
    ports:
      # DataPackagePort
      # EXPOSE 8080
      # CoTPort
      # EXPOSE 8087
      # SSLCoTPort
      - "8089:8089"
      # SSLDataPackagePort
      #EXPOSE 8443
      # FederationPort
      #EXPOSE 9000
      # APIPort
      - "19023:19023"
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    restart: always
    volumes:
      - "./ui/config.py:/fts-ui/FreeTAKServer-UI/config.py"
      - "./ui:/opt/fts-ui"

    ports:
      - "5001:5000"

  webmap:
    build:
      context: .
      dockerfile: Dockerfile.webmap
    restart: always
    volumes:
      - "./webmap/config.json:/webmap/config.json"
    ports:
      - "8000:8000"